# Data paths
train_path: data/tokens/owt-train.bin
valid_path: data/tokens/owt-val.bin

# Model parameters
vocab_size: 32000
context_length: 512
num_layers: 4
num_heads: 16
d_model: 512
d_ff: 1344
rope_theta: 10000.0

# Optimizer parameters
weight_decay: 0.1
beta1: 0.9
beta2: 0.99

max_l2_norm: 1.0

# scheduler parameters
lr_max: 0.006
lr_min_ratio: 0.05
warmup_pct: 0.05
cooldown_pct: 0.8

# Training parameters
batch_size: 128
max_iters: 7500

# Logging and evaluation
log_interval: 20
activation_log_interval: 100
wandb_project: "cs336-assignment-owt"
wandb_run_name: "weight_tying_trapezoidal_lr0.006_bs128"

# Evaluation
eval_interval: 400
eval_num_batches: 200

# Checkpointing
checkpoint_interval: 10000
checkpoint_dir: checkpoints
resume_from: null

# model config
tie_word_embeddings: true
use_qk_norm: false
scheduler_type: "trapezoidal"

# Misc
device: cuda
seed: 123